### ISSUE TITLE
Error when running the LIRAGE in NQ-TABLES dataset

### ISSUE THREAD

**Issue by bianzheng123** [amazon-science/robust-tableqa#3]
Hello,
First of all, I want to express my gratitude for the excellent work you've been doing.

I am a beginner in the information retrieval area and I am sorry to raise this question.
The error happened when I tried to run the code the first time.
Here is the log information.

Traceback (most recent call last):
  File "src/main.py", line 427, in <module>
    main()
  File "src/main.py", line 344, in main
    data_loader_manager.build_dataset()
  File "/home/xxx/robust-tableqa/src/data_loader_manager/data_loader_wrapper.py", line 139, in build_dataset
    loading_func(module_config)
  File "/home/xxx/robust-tableqa/src/data_loader_manager/data_loader_for_tableqa.py", line 1427, in LoadNQTableData
    raise Exception("Please generate BM25 results first.")

The error could be located in lines 1421 to 1429. 
With analysis, the code does not raise an exception when (1) it finds the split_cache_path and (2) it finds the bm25_results_path
I guess split_cache_path and bm25_results_path are related to the dataset (NQ-TABLES) itself. 
However, I could not find both files in the data source or this GitHub repository. 
Could you please provide that file to me?

**Comment by LinWeizheDragon** [comment]
Hi, BM25 results were extracted offline. They were used as a source of negative examples in one of my experiments. However, the experiments showed that they are not better than randomly chosen negative examples. So I think you can simply ignore the BM25 part (do whatever that works).
